title: "SIMD2020-Data"
description: "Analysis of Council Area Deprivation Levels"
logo: "" # Add path to logo file here if you have one, e.g. /assets/img/logo.png
show_downloads: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
